// Code generated by Kitex v0.11.3. DO NOT EDIT.

package helloworldservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	hello_world "monorepo/service/rpc/hello_word/kitex_gen/monorepo/rpc/hello_world"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	GetHelloWorld(ctx context.Context, req *hello_world.GetHelloWorldRequest, callOptions ...callopt.Option) (r *hello_world.GetHelloWorldResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kHelloWorldServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kHelloWorldServiceClient struct {
	*kClient
}

func (p *kHelloWorldServiceClient) GetHelloWorld(ctx context.Context, req *hello_world.GetHelloWorldRequest, callOptions ...callopt.Option) (r *hello_world.GetHelloWorldResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetHelloWorld(ctx, req)
}
