// Code generated by Kitex v0.11.3. DO NOT EDIT.

package helloworldservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	hello_world "monorepo/service/rpc/hello_word/kitex_gen/monorepo/rpc/hello_world"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"getHelloWorld": kitex.NewMethodInfo(
		getHelloWorldHandler,
		newHelloWorldServiceGetHelloWorldArgs,
		newHelloWorldServiceGetHelloWorldResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	helloWorldServiceServiceInfo                = NewServiceInfo()
	helloWorldServiceServiceInfoForClient       = NewServiceInfoForClient()
	helloWorldServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return helloWorldServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return helloWorldServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return helloWorldServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "HelloWorldService"
	handlerType := (*hello_world.HelloWorldService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "hello_world",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.11.3",
		Extra:           extra,
	}
	return svcInfo
}

func getHelloWorldHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*hello_world.HelloWorldServiceGetHelloWorldArgs)
	realResult := result.(*hello_world.HelloWorldServiceGetHelloWorldResult)
	success, err := handler.(hello_world.HelloWorldService).GetHelloWorld(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newHelloWorldServiceGetHelloWorldArgs() interface{} {
	return hello_world.NewHelloWorldServiceGetHelloWorldArgs()
}

func newHelloWorldServiceGetHelloWorldResult() interface{} {
	return hello_world.NewHelloWorldServiceGetHelloWorldResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) GetHelloWorld(ctx context.Context, req *hello_world.GetHelloWorldRequest) (r *hello_world.GetHelloWorldResponse, err error) {
	var _args hello_world.HelloWorldServiceGetHelloWorldArgs
	_args.Req = req
	var _result hello_world.HelloWorldServiceGetHelloWorldResult
	if err = p.c.Call(ctx, "getHelloWorld", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
